/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Action =
    | "key"
    | "type"
    | "mouse_move"
    | "left_click"
    | "left_click_drag"
    | "right_click"
    | "middle_click"
    | "double_click"
    | "screenshot"
    | "cursor_position";

export const Action = {
    Key: "key",
    Type: "type",
    MouseMove: "mouse_move",
    LeftClick: "left_click",
    LeftClickDrag: "left_click_drag",
    RightClick: "right_click",
    MiddleClick: "middle_click",
    DoubleClick: "double_click",
    Screenshot: "screenshot",
    CursorPosition: "cursor_position",
} as const;
