/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Command = "view" | "create" | "str_replace" | "insert" | "undo_edit";
export const Command = {
    View: "view",
    Create: "create",
    StrReplace: "str_replace",
    Insert: "insert",
    UndoEdit: "undo_edit",
} as const;
