/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../../../index";

export type Request =
    | Scrapybara.Request.MoveMouse
    | Scrapybara.Request.ClickMouse
    | Scrapybara.Request.DragMouse
    | Scrapybara.Request.Scroll
    | Scrapybara.Request.PressKey
    | Scrapybara.Request.TypeText
    | Scrapybara.Request.Wait
    | Scrapybara.Request.TakeScreenshot
    | Scrapybara.Request.GetCursorPosition;

export namespace Request {
    export interface MoveMouse extends Scrapybara.MoveMouseAction {
        action: "move_mouse";
    }

    export interface ClickMouse extends Scrapybara.ClickMouseAction {
        action: "click_mouse";
    }

    export interface DragMouse extends Scrapybara.DragMouseAction {
        action: "drag_mouse";
    }

    export interface Scroll extends Scrapybara.ScrollAction {
        action: "scroll";
    }

    export interface PressKey extends Scrapybara.PressKeyAction {
        action: "press_key";
    }

    export interface TypeText extends Scrapybara.TypeTextAction {
        action: "type_text";
    }

    export interface Wait extends Scrapybara.WaitAction {
        action: "wait";
    }

    export interface TakeScreenshot extends Scrapybara.TakeScreenshotAction {
        action: "take_screenshot";
    }

    export interface GetCursorPosition extends Scrapybara.GetCursorPositionAction {
        action: "get_cursor_position";
    }
}
