/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         variables: {
 *             "key": "value"
 *         }
 *     }
 */
export interface EnvSetRequest {
    variables: Record<string, string>;
}
