/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FetchHtml200Response {
    /**
    * The raw HTML content of the requested URL.
    */
    'html'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "html",
            "baseName": "html",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FetchHtml200Response.attributeTypeMap;
    }
}

