/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ScriptExecutionRequest {
    /**
    * Unique identifier of the script to be executed.
    */
    'scriptId': string;
    /**
    * If true, the execution results will be streamed as they\'re generated.
    */
    'streaming'?: boolean = false;
    /**
    * If true, applies advanced processing to improve data extraction results.
    */
    'magic'?: boolean = false;
    /**
    * Optional URL to override the script\'s default target URL.
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scriptId",
            "baseName": "script_id",
            "type": "string"
        },
        {
            "name": "streaming",
            "baseName": "streaming",
            "type": "boolean"
        },
        {
            "name": "magic",
            "baseName": "magic",
            "type": "boolean"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScriptExecutionRequest.attributeTypeMap;
    }
}

