/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ScriptGenerationStreamingResponse {
    /**
    * Unique identifier for the generated script.
    */
    'scriptId': string;
    /**
    * The current status of script generation (e.g., \'in_progress\', \'completed\', \'error\').
    */
    'status': string;
    /**
    * Additional details about the generation status or errors.
    */
    'statusDescription': string;
    /**
    * The current version of the generated script.
    */
    'currentScript'?: string;
    /**
    * The result of executing the current version of the script.
    */
    'currentScriptExecutionResult'?: string;
    /**
    * Explanation of the reasoning behind the current script version.
    */
    'reasoning'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "scriptId",
            "baseName": "script_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "statusDescription",
            "baseName": "status_description",
            "type": "string"
        },
        {
            "name": "currentScript",
            "baseName": "current_script",
            "type": "string"
        },
        {
            "name": "currentScriptExecutionResult",
            "baseName": "current_script_execution_result",
            "type": "string"
        },
        {
            "name": "reasoning",
            "baseName": "reasoning",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScriptGenerationStreamingResponse.attributeTypeMap;
    }
}

