/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ScriptGenerationRequest {
    /**
    * The target URL for the script.
    */
    'url': string;
    /**
    * The action to be performed by the script.
    */
    'command': string;
    /**
    * Optional step-by-step instructions for complex actions.
    */
    'steps'?: Array<string>;
    /**
    * If true, the response will be streamed as it\'s generated.
    */
    'streaming'?: boolean = false;
    /**
    * Optional schema defining the structure of input data.
    */
    'inputSchema'?: object;
    /**
    * Optional schema defining the expected structure of output data.
    */
    'outputSchema'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "Array<string>"
        },
        {
            "name": "streaming",
            "baseName": "streaming",
            "type": "boolean"
        },
        {
            "name": "inputSchema",
            "baseName": "input_schema",
            "type": "object"
        },
        {
            "name": "outputSchema",
            "baseName": "output_schema",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return ScriptGenerationRequest.attributeTypeMap;
    }
}

