/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ScriptDetails {
    /**
    * Unique identifier of the script.
    */
    'id'?: string;
    /**
    * The target URL for the script.
    */
    'url'?: string;
    /**
    * The original action or instructions.
    */
    'command'?: string;
    /**
    * Detailed steps for the action.
    */
    'steps'?: object;
    /**
    * The actual code content of the script.
    */
    'content'?: string;
    /**
    * Current status of the script (e.g., \'pending\', \'completed\', \'error\').
    */
    'status'?: string;
    /**
    * Additional details about the script\'s status.
    */
    'statusDescription'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "steps",
            "baseName": "steps",
            "type": "object"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "statusDescription",
            "baseName": "status_description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ScriptDetails.attributeTypeMap;
    }
}

