/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scrapybara from "../../../../api/index";
import * as core from "../../../../core";

export const Action: core.serialization.Schema<serializers.Action.Raw, Scrapybara.Action> = core.serialization.enum_([
    "key",
    "type",
    "mouse_move",
    "left_click",
    "left_click_drag",
    "right_click",
    "middle_click",
    "double_click",
    "screenshot",
    "cursor_position",
    "scroll",
    "wait",
]);

export declare namespace Action {
    export type Raw =
        | "key"
        | "type"
        | "mouse_move"
        | "left_click"
        | "left_click_drag"
        | "right_click"
        | "middle_click"
        | "double_click"
        | "screenshot"
        | "cursor_position"
        | "scroll"
        | "wait";
}
