/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scrapybara from "../../../../api/index";
import * as core from "../../../../core";

export const Command: core.serialization.Schema<serializers.Command.Raw, Scrapybara.Command> = core.serialization.enum_(
    ["view", "create", "str_replace", "insert", "undo_edit"],
);

export declare namespace Command {
    export type Raw = "view" | "create" | "str_replace" | "insert" | "undo_edit";
}
