/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scrapybara from "../../../../api/index";
import * as core from "../../../../core";
import { MoveMouseAction } from "../../../types/MoveMouseAction";
import { ClickMouseAction } from "../../../types/ClickMouseAction";
import { DragMouseAction } from "../../../types/DragMouseAction";
import { ScrollAction } from "../../../types/ScrollAction";
import { PressKeyAction } from "../../../types/PressKeyAction";
import { TypeTextAction } from "../../../types/TypeTextAction";
import { WaitAction } from "../../../types/WaitAction";
import { TakeScreenshotAction } from "../../../types/TakeScreenshotAction";
import { GetCursorPositionAction } from "../../../types/GetCursorPositionAction";

export const Request: core.serialization.Schema<serializers.Request.Raw, Scrapybara.Request> = core.serialization
    .union("action", {
        move_mouse: MoveMouseAction,
        click_mouse: ClickMouseAction,
        drag_mouse: DragMouseAction,
        scroll: ScrollAction,
        press_key: PressKeyAction,
        type_text: TypeTextAction,
        wait: WaitAction,
        take_screenshot: TakeScreenshotAction,
        get_cursor_position: GetCursorPositionAction,
    })
    .transform<Scrapybara.Request>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace Request {
    export type Raw =
        | Request.MoveMouse
        | Request.ClickMouse
        | Request.DragMouse
        | Request.Scroll
        | Request.PressKey
        | Request.TypeText
        | Request.Wait
        | Request.TakeScreenshot
        | Request.GetCursorPosition;

    export interface MoveMouse extends MoveMouseAction.Raw {
        action: "move_mouse";
    }

    export interface ClickMouse extends ClickMouseAction.Raw {
        action: "click_mouse";
    }

    export interface DragMouse extends DragMouseAction.Raw {
        action: "drag_mouse";
    }

    export interface Scroll extends ScrollAction.Raw {
        action: "scroll";
    }

    export interface PressKey extends PressKeyAction.Raw {
        action: "press_key";
    }

    export interface TypeText extends TypeTextAction.Raw {
        action: "type_text";
    }

    export interface Wait extends WaitAction.Raw {
        action: "wait";
    }

    export interface TakeScreenshot extends TakeScreenshotAction.Raw {
        action: "take_screenshot";
    }

    export interface GetCursorPosition extends GetCursorPositionAction.Raw {
        action: "get_cursor_position";
    }
}
