/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const ScrapeRequest: core.serialization.Schema<serializers.ScrapeRequest.Raw, Scrapybara.ScrapeRequest> =
    core.serialization.object({
        cmd: core.serialization.string(),
        schema: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        includeScreenshot: core.serialization.property("include_screenshot", core.serialization.boolean().optional()),
        model: core.serialization.stringLiteral("claude").optional(),
    });

export declare namespace ScrapeRequest {
    interface Raw {
        cmd: string;
        schema?: Record<string, unknown> | null;
        include_screenshot?: boolean | null;
        model?: "claude" | null;
    }
}
