/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         path: "path"
 *     }
 */
export interface FileReadFileRequest {
    path: string;
    encoding?: string;
}
