/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         path: "path",
 *         content: "content"
 *     }
 */
export interface FileUploadRequest {
    path: string;
    content: string;
}
