/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as ScrapybaraApi from "../../../index";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization/index";
import * as errors from "../../../../errors/index";

export declare namespace Browser {
    interface Options {
        environment?: core.Supplier<environments.ScrapybaraApiEnvironment | string>;
        /** Override the authorization header */
        authorization: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the authorization header */
        authorization?: string;
    }
}

export class Browser {
    constructor(protected readonly _options: Browser.Options) {}

    /**
     * @param {string} instanceId
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ScrapybaraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browser.start("instance_id")
     */
    public async start(
        instanceId: string,
        requestOptions?: Browser.RequestOptions
    ): Promise<ScrapybaraApi.StartBrowserResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.ScrapybaraApiEnvironment.Default,
                `v1/instance/${encodeURIComponent(instanceId)}/browser/start`
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "scrapybara",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "scrapybara/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.StartBrowserResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new ScrapybaraApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.ScrapybaraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ScrapybaraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ScrapybaraApiTimeoutError();
            case "unknown":
                throw new errors.ScrapybaraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * @param {string} instanceId
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ScrapybaraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browser.getCdpUrl("instance_id")
     */
    public async getCdpUrl(
        instanceId: string,
        requestOptions?: Browser.RequestOptions
    ): Promise<ScrapybaraApi.BrowserGetCdpUrlResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.ScrapybaraApiEnvironment.Default,
                `v1/instance/${encodeURIComponent(instanceId)}/browser/cdp_url`
            ),
            method: "GET",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "scrapybara",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "scrapybara/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.BrowserGetCdpUrlResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new ScrapybaraApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.ScrapybaraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ScrapybaraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ScrapybaraApiTimeoutError();
            case "unknown":
                throw new errors.ScrapybaraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Authenticate browser with Anon for all available apps
     *
     * @param {string} instanceId
     * @param {ScrapybaraApi.BrowserAuthenticateRequest} request
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ScrapybaraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browser.authenticate("instance_id", {
     *         contextId: "context_id"
     *     })
     */
    public async authenticate(
        instanceId: string,
        request: ScrapybaraApi.BrowserAuthenticateRequest,
        requestOptions?: Browser.RequestOptions
    ): Promise<ScrapybaraApi.BrowserAuthenticateResponse> {
        const { contextId } = request;
        const _queryParams: Record<string, string | string[] | object | object[]> = {};
        _queryParams["context_id"] = contextId;
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.ScrapybaraApiEnvironment.Default,
                `v1/instance/${encodeURIComponent(instanceId)}/browser/authenticate`
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "scrapybara",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "scrapybara/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.BrowserAuthenticateResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new ScrapybaraApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.ScrapybaraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ScrapybaraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ScrapybaraApiTimeoutError();
            case "unknown":
                throw new errors.ScrapybaraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * @param {string} instanceId
     * @param {Browser.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ScrapybaraApi.UnprocessableEntityError}
     *
     * @example
     *     await client.browser.stop("instance_id")
     */
    public async stop(
        instanceId: string,
        requestOptions?: Browser.RequestOptions
    ): Promise<ScrapybaraApi.StopBrowserResponse> {
        const _response = await core.fetcher({
            url: urlJoin(
                (await core.Supplier.get(this._options.environment)) ?? environments.ScrapybaraApiEnvironment.Default,
                `v1/instance/${encodeURIComponent(instanceId)}/browser/stop`
            ),
            method: "POST",
            headers: {
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "scrapybara",
                "X-Fern-SDK-Version": "0.1.0",
                "User-Agent": "scrapybara/0.1.0",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...(await this._getCustomAuthorizationHeaders()),
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return serializers.StopBrowserResponse.parseOrThrow(_response.body, {
                unrecognizedObjectKeys: "passthrough",
                allowUnrecognizedUnionMembers: true,
                allowUnrecognizedEnumValues: true,
                breadcrumbsPrefix: ["response"],
            });
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new ScrapybaraApi.UnprocessableEntityError(
                        serializers.HttpValidationError.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            breadcrumbsPrefix: ["response"],
                        })
                    );
                default:
                    throw new errors.ScrapybaraApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ScrapybaraApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ScrapybaraApiTimeoutError();
            case "unknown":
                throw new errors.ScrapybaraApiError({
                    message: _response.error.errorMessage,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const authorizationValue = await core.Supplier.get(this._options.authorization);
        return { authorization: authorizationValue };
    }
}
