/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { AuthStateResponse } from "../types/AuthStateResponse";

export const Response: core.serialization.Schema<
    serializers.getAuthStates.Response.Raw,
    Scrapybara.AuthStateResponse[]
> = core.serialization.list(AuthStateResponse);

export declare namespace Response {
    export type Raw = AuthStateResponse.Raw[];
}
