/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { GetInstanceResponse } from "../types/GetInstanceResponse";

export const Response: core.serialization.Schema<
    serializers.getInstances.Response.Raw,
    Scrapybara.GetInstanceResponse[]
> = core.serialization.list(GetInstanceResponse);

export declare namespace Response {
    export type Raw = GetInstanceResponse.Raw[];
}
