/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scrapybara from "../../../../api/index";
import * as core from "../../../../core";

export const Model: core.serialization.Schema<serializers.Model.Raw, Scrapybara.Model> = core.serialization.enum_([
    "claude",
    "gemini",
]);

export declare namespace Model {
    export type Raw = "claude" | "gemini";
}
