/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BashRequest {
    command?: string;
    session?: number;
    restart?: boolean;
    listSessions?: boolean;
    checkSession?: number;
    timeout?: number;
}
