/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface BashRequest {
    command?: string;
    restart?: boolean;
    getBackgroundProcesses?: boolean;
    killPid?: number;
}
