/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../../../../index";

/**
 * @example
 *     {
 *         action: "key"
 *     }
 */
export interface ComputerRequest {
    action: Scrapybara.Action;
    coordinate?: number[];
    text?: string;
}
