/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ScrapybaraApi from "../../../../index";

/**
 * @example
 *     {
 *         action: ScrapybaraApi.Action.Key
 *     }
 */
export interface ComputerRequest {
    action: ScrapybaraApi.Action;
    coordinate?: number[];
    text?: string;
}
