/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ScrapybaraApi from "../../../../index";

/**
 * @example
 *     {
 *         command: ScrapybaraApi.Command.View,
 *         path: "path"
 *     }
 */
export interface EditRequest {
    command: ScrapybaraApi.Command;
    path: string;
    fileText?: string;
    viewRange?: number[];
    oldStr?: string;
    newStr?: string;
    insertLine?: number;
}
