/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         command: "command"
 *     }
 */
export interface FileRequest {
    command: string;
    path?: string;
    content?: string;
    mode?: string;
    encoding?: string;
    viewRange?: number[];
    recursive?: boolean;
    src?: string;
    dst?: string;
    oldStr?: string;
    newStr?: string;
    line?: number;
    text?: string;
    lines?: number[];
    allOccurrences?: boolean;
    pattern?: string;
    caseSensitive?: boolean;
    lineNumbers?: boolean;
}
