/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         path: "path",
 *         localPath: "local_path"
 *     }
 */
export interface InstanceDownloadRequest {
    path: string;
    localPath: string;
}
