/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         directoryPath: "directory_path"
 *     }
 */
export interface NetlifyDeployRequest {
    directoryPath: string;
}
