/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ScrapybaraApi from "../../../../index";

/**
 * @example
 *     {}
 */
export interface DeploymentConfig {
    instanceType?: ScrapybaraApi.DeploymentConfigInstanceType;
    timeoutHours?: number;
}
