/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../../../../index";

/**
 * @example
 *     {
 *         type: "code",
 *         content: "content"
 *     }
 */
export interface AddCellRequest {
    type: Scrapybara.CellType;
    content: string;
    metadata?: Record<string, unknown>;
}
