/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         kernelName: "kernel_name"
 *     }
 */
export interface CreateNotebookRequest {
    name: string;
    kernelName: string;
}
