/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         authStateId: "auth_state_id"
 *     }
 */
export interface BrowserModifyAuthRequest {
    authStateId: string;
    name?: string;
}
