/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../index";
import * as Scrapybara from "../../../api/index";
import * as core from "../../../core";
import { DeploymentConfigInstanceType } from "../../types/DeploymentConfigInstanceType";

export const DeploymentConfig: core.serialization.Schema<
    serializers.DeploymentConfig.Raw,
    Scrapybara.DeploymentConfig
> = core.serialization.object({
    instanceType: core.serialization.property("instance_type", DeploymentConfigInstanceType.optional()),
    timeoutHours: core.serialization.property("timeout_hours", core.serialization.number().optional()),
});

export declare namespace DeploymentConfig {
    export interface Raw {
        instance_type?: DeploymentConfigInstanceType.Raw | null;
        timeout_hours?: number | null;
    }
}
