/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const CodeExecuteRequest: core.serialization.Schema<
    serializers.CodeExecuteRequest.Raw,
    Scrapybara.CodeExecuteRequest
> = core.serialization.object({
    code: core.serialization.string(),
    kernelName: core.serialization.property("kernel_name", core.serialization.string().optional()),
    timeout: core.serialization.number().optional(),
});

export declare namespace CodeExecuteRequest {
    export interface Raw {
        code: string;
        kernel_name?: string | null;
        timeout?: number | null;
    }
}
