/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const FileUploadRequest: core.serialization.Schema<
    serializers.FileUploadRequest.Raw,
    Scrapybara.FileUploadRequest
> = core.serialization.object({
    path: core.serialization.string(),
    content: core.serialization.string(),
});

export declare namespace FileUploadRequest {
    export interface Raw {
        path: string;
        content: string;
    }
}
