/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const FileWriteRequest: core.serialization.Schema<
    serializers.FileWriteRequest.Raw,
    Scrapybara.FileWriteRequest
> = core.serialization.object({
    path: core.serialization.string(),
    content: core.serialization.string(),
    encoding: core.serialization.string().optional(),
});

export declare namespace FileWriteRequest {
    export interface Raw {
        path: string;
        content: string;
        encoding?: string | null;
    }
}
