/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const BashRequest: core.serialization.Schema<serializers.BashRequest.Raw, Scrapybara.BashRequest> =
    core.serialization.object({
        command: core.serialization.string().optional(),
        session: core.serialization.number().optional(),
        restart: core.serialization.boolean().optional(),
        listSessions: core.serialization.property("list_sessions", core.serialization.boolean().optional()),
        checkSession: core.serialization.property("check_session", core.serialization.number().optional()),
        timeout: core.serialization.number().optional(),
    });

export declare namespace BashRequest {
    export interface Raw {
        command?: string | null;
        session?: number | null;
        restart?: boolean | null;
        list_sessions?: boolean | null;
        check_session?: number | null;
        timeout?: number | null;
    }
}
