/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const BashRequest: core.serialization.Schema<serializers.BashRequest.Raw, Scrapybara.BashRequest> =
    core.serialization.object({
        command: core.serialization.string().optional(),
        restart: core.serialization.boolean().optional(),
        getBackgroundProcesses: core.serialization.property(
            "get_background_processes",
            core.serialization.boolean().optional(),
        ),
        killPid: core.serialization.property("kill_pid", core.serialization.number().optional()),
    });

export declare namespace BashRequest {
    export interface Raw {
        command?: string | null;
        restart?: boolean | null;
        get_background_processes?: boolean | null;
        kill_pid?: number | null;
    }
}
