/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const BashRequest: core.serialization.Schema<serializers.BashRequest.Raw, Scrapybara.BashRequest> =
    core.serialization.object({
        command: core.serialization.string().optional(),
        restart: core.serialization.boolean().optional(),
    });

export declare namespace BashRequest {
    interface Raw {
        command?: string | null;
        restart?: boolean | null;
    }
}
