/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as ScrapybaraApi from "../../../../../api/index";
import * as core from "../../../../../core";
import { Action } from "../../types/Action";

export const ComputerRequest: core.serialization.Schema<
    serializers.ComputerRequest.Raw,
    ScrapybaraApi.ComputerRequest
> = core.serialization.object({
    action: Action,
    coordinate: core.serialization.list(core.serialization.number()).optional(),
    text: core.serialization.string().optional(),
});

export declare namespace ComputerRequest {
    interface Raw {
        action: Action.Raw;
        coordinate?: number[] | null;
        text?: string | null;
    }
}
