/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";
import { Command } from "../../types/Command";

export const EditRequest: core.serialization.Schema<serializers.EditRequest.Raw, Scrapybara.EditRequest> =
    core.serialization.object({
        command: Command,
        path: core.serialization.string(),
        fileText: core.serialization.property("file_text", core.serialization.string().optional()),
        viewRange: core.serialization.property(
            "view_range",
            core.serialization.list(core.serialization.number()).optional(),
        ),
        oldStr: core.serialization.property("old_str", core.serialization.string().optional()),
        newStr: core.serialization.property("new_str", core.serialization.string().optional()),
        insertLine: core.serialization.property("insert_line", core.serialization.number().optional()),
    });

export declare namespace EditRequest {
    export interface Raw {
        command: Command.Raw;
        path: string;
        file_text?: string | null;
        view_range?: number[] | null;
        old_str?: string | null;
        new_str?: string | null;
        insert_line?: number | null;
    }
}
