/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const ExposePortRequest: core.serialization.Schema<
    serializers.ExposePortRequest.Raw,
    Scrapybara.ExposePortRequest
> = core.serialization.object({
    port: core.serialization.number(),
});

export declare namespace ExposePortRequest {
    export interface Raw {
        port: number;
    }
}
