/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const FileRequest: core.serialization.Schema<serializers.FileRequest.Raw, Scrapybara.FileRequest> =
    core.serialization.object({
        command: core.serialization.string(),
        path: core.serialization.string().optional(),
        content: core.serialization.string().optional(),
        mode: core.serialization.string().optional(),
        encoding: core.serialization.string().optional(),
        viewRange: core.serialization.property(
            "view_range",
            core.serialization.list(core.serialization.number()).optional(),
        ),
        recursive: core.serialization.boolean().optional(),
        src: core.serialization.string().optional(),
        dst: core.serialization.string().optional(),
        oldStr: core.serialization.property("old_str", core.serialization.string().optional()),
        newStr: core.serialization.property("new_str", core.serialization.string().optional()),
        line: core.serialization.number().optional(),
        text: core.serialization.string().optional(),
        lines: core.serialization.list(core.serialization.number()).optional(),
        allOccurrences: core.serialization.property("all_occurrences", core.serialization.boolean().optional()),
        pattern: core.serialization.string().optional(),
        caseSensitive: core.serialization.property("case_sensitive", core.serialization.boolean().optional()),
        lineNumbers: core.serialization.property("line_numbers", core.serialization.boolean().optional()),
    });

export declare namespace FileRequest {
    export interface Raw {
        command: string;
        path?: string | null;
        content?: string | null;
        mode?: string | null;
        encoding?: string | null;
        view_range?: number[] | null;
        recursive?: boolean | null;
        src?: string | null;
        dst?: string | null;
        old_str?: string | null;
        new_str?: string | null;
        line?: number | null;
        text?: string | null;
        lines?: number[] | null;
        all_occurrences?: boolean | null;
        pattern?: string | null;
        case_sensitive?: boolean | null;
        line_numbers?: boolean | null;
    }
}
