/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const NetlifyDeployRequest: core.serialization.Schema<
    serializers.NetlifyDeployRequest.Raw,
    Scrapybara.NetlifyDeployRequest
> = core.serialization.object({
    directoryPath: core.serialization.property("directory_path", core.serialization.string()),
});

export declare namespace NetlifyDeployRequest {
    export interface Raw {
        directory_path: string;
    }
}
