/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export type Action =
    | Scrapybara.Action.ClickMouse
    | Scrapybara.Action.DragMouse
    | Scrapybara.Action.GetCursorPosition
    | Scrapybara.Action.MoveMouse
    | Scrapybara.Action.PressKey
    | Scrapybara.Action.Scroll
    | Scrapybara.Action.TakeScreenshot
    | Scrapybara.Action.TypeText
    | Scrapybara.Action.Wait;

export namespace Action {
    export interface ClickMouse extends Scrapybara.ClickMouseAction {
        action: "click_mouse";
    }

    export interface DragMouse extends Scrapybara.DragMouseAction {
        action: "drag_mouse";
    }

    export interface GetCursorPosition extends Scrapybara.GetCursorPositionAction {
        action: "get_cursor_position";
    }

    export interface MoveMouse extends Scrapybara.MoveMouseAction {
        action: "move_mouse";
    }

    export interface PressKey extends Scrapybara.PressKeyAction {
        action: "press_key";
    }

    export interface Scroll extends Scrapybara.ScrollAction {
        action: "scroll";
    }

    export interface TakeScreenshot extends Scrapybara.TakeScreenshotAction {
        action: "take_screenshot";
    }

    export interface TypeText extends Scrapybara.TypeTextAction {
        action: "type_text";
    }

    export interface Wait extends Scrapybara.WaitAction {
        action: "wait";
    }
}
