/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for bash actions.
 */
export interface BashResponse {
    output?: string;
    error?: string;
    base64Image?: string;
    system?: string;
}
