/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Button = "left" | "right" | "middle" | "back" | "forward";
export const Button = {
    Left: "left",
    Right: "right",
    Middle: "middle",
    Back: "back",
    Forward: "forward",
} as const;
