/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CellType = "code" | "markdown" | "raw";
export const CellType = {
    Code: "code",
    Markdown: "markdown",
    Raw: "raw",
} as const;
