/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClickMouseActionClickType = "down" | "up" | "click";
export const ClickMouseActionClickType = {
    Down: "down",
    Up: "up",
    Click: "click",
} as const;
