/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export interface ClickMouseAction {
    button: Scrapybara.Button;
    clickType?: Scrapybara.ClickMouseActionClickType;
    coordinates?: number[];
    numClicks?: number;
    holdKeys?: string[];
    screenshot?: boolean;
}
