/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export interface ComputerRequest {
    action: Scrapybara.Action;
    screenshot?: boolean;
}
