/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for filesystem actions.
 */
export interface FilesystemResponse {
    output?: string;
    error?: string;
    base64Image?: string;
    system?: string;
}
