/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ScrapybaraApi from "../index";

export interface GetInstanceResponse {
    id: string;
    launchTime: Date;
    instanceType: string;
    status: ScrapybaraApi.Status;
}
