/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export interface GetInstanceResponse {
    id: string;
    launchTime: Date;
    instanceType: Scrapybara.GetInstanceResponseInstanceType;
    status: Scrapybara.Status;
    resolution?: number[];
}
