/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type GetInstanceResponseInstanceType = "ubuntu" | "browser" | "windows";
export const GetInstanceResponseInstanceType = {
    Ubuntu: "ubuntu",
    Browser: "browser",
    Windows: "windows",
} as const;
