/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ScrapybaraApi from "../index";

export interface HttpValidationError {
    detail?: ScrapybaraApi.ValidationError[];
}
