/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for netlify deployment.
 */
export interface NetlifyDeployResponse {
    output?: string;
    error?: string;
    siteUrl?: string;
}
