/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export interface Notebook {
    id: string;
    name: string;
    kernelName: string;
    cells: Scrapybara.NotebookCell[];
    metadata?: Record<string, unknown>;
}
