/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export interface NotebookCell {
    id: string;
    type: Scrapybara.CellType;
    content: string;
    metadata?: Record<string, unknown>;
    outputs?: Record<string, unknown>[];
    executionCount?: number;
}
