/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ScrollAction {
    coordinates?: number[];
    deltaX?: number;
    deltaY?: number;
    holdKeys?: string[];
    screenshot?: boolean;
}
