/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "deploying" | "running" | "terminated" | "error";
export const Status = {
    Deploying: "deploying",
    Running: "running",
    Terminated: "terminated",
    Error: "error",
} as const;
