/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "deploying" | "running" | "paused" | "terminated" | "error" | "warm_pool";
export const Status = {
    Deploying: "deploying",
    Running: "running",
    Paused: "paused",
    Terminated: "terminated",
    Error: "error",
    WarmPool: "warm_pool",
} as const;
