/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for file uploads.
 */
export interface UploadResponse {
    filename: string;
    path: string;
    mediaType?: string;
}
