/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../index";

export interface ValidationError {
    loc: Scrapybara.ValidationErrorLocItem[];
    msg: string;
    type: string;
}
