/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const EnvDeleteRequest: core.serialization.Schema<
    serializers.EnvDeleteRequest.Raw,
    Scrapybara.EnvDeleteRequest
> = core.serialization.object({
    keys: core.serialization.list(core.serialization.string()),
});

export declare namespace EnvDeleteRequest {
    export interface Raw {
        keys: string[];
    }
}
