/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const EnvSetRequest: core.serialization.Schema<serializers.EnvSetRequest.Raw, Scrapybara.EnvSetRequest> =
    core.serialization.object({
        variables: core.serialization.record(core.serialization.string(), core.serialization.string()),
    });

export declare namespace EnvSetRequest {
    export interface Raw {
        variables: Record<string, string>;
    }
}
