/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scrapybara from "../../../../api/index";
import * as core from "../../../../core";
import { NotebookCell } from "../../../types/NotebookCell";

export const Response: core.serialization.Schema<serializers.notebook.execute.Response.Raw, Scrapybara.NotebookCell[]> =
    core.serialization.list(NotebookCell);

export declare namespace Response {
    export type Raw = NotebookCell.Raw[];
}
