/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Scrapybara from "../../../../api/index";
import * as core from "../../../../core";
import { KernelInfo } from "../../../types/KernelInfo";

export const Response: core.serialization.Schema<
    serializers.notebook.listKernels.Response.Raw,
    Scrapybara.KernelInfo[]
> = core.serialization.list(KernelInfo);

export declare namespace Response {
    export type Raw = KernelInfo.Raw[];
}
