/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../../index";

/**
 * @example
 *     {}
 */
export interface DeploymentConfig {
    instanceType?: Scrapybara.DeploymentConfigInstanceType;
    timeoutHours?: number;
    blockedDomains?: string[];
    resolution?: number[];
    backend?: string;
    snapshotId?: string;
}
