/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenerateScriptRequest,
  GenerateScriptResponse,
} from '../models/index';
import {
    GenerateScriptRequestFromJSON,
    GenerateScriptRequestToJSON,
    GenerateScriptResponseFromJSON,
    GenerateScriptResponseToJSON,
} from '../models/index';

export interface GenerateScriptOperationRequest {
    generateScriptRequest: GenerateScriptRequest;
}

/**
 * 
 */
export class ScriptGenerationApi extends runtime.BaseAPI {

    /**
     * Auto-generates a new script. Use \'streaming\' to get real-time updates on the script generation process.
     * Generate script
     */
    async generateScriptRaw(requestParameters: GenerateScriptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateScriptResponse>> {
        if (requestParameters['generateScriptRequest'] == null) {
            throw new runtime.RequiredError(
                'generateScriptRequest',
                'Required parameter "generateScriptRequest" was null or undefined when calling generateScript().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/scripts/generate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateScriptRequestToJSON(requestParameters['generateScriptRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateScriptResponseFromJSON(jsonValue));
    }

    /**
     * Auto-generates a new script. Use \'streaming\' to get real-time updates on the script generation process.
     * Generate script
     */
    async generateScript(requestParameters: GenerateScriptOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateScriptResponse> {
        const response = await this.generateScriptRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
