/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { ClickMouseAction } from "./ClickMouseAction";
import { DragMouseAction } from "./DragMouseAction";
import { GetCursorPositionAction } from "./GetCursorPositionAction";
import { MoveMouseAction } from "./MoveMouseAction";
import { PressKeyAction } from "./PressKeyAction";
import { ScrollAction } from "./ScrollAction";
import { TakeScreenshotAction } from "./TakeScreenshotAction";
import { TypeTextAction } from "./TypeTextAction";
import { WaitAction } from "./WaitAction";

export const Action: core.serialization.Schema<serializers.Action.Raw, Scrapybara.Action> = core.serialization
    .union("action", {
        click_mouse: ClickMouseAction,
        drag_mouse: DragMouseAction,
        get_cursor_position: GetCursorPositionAction,
        move_mouse: MoveMouseAction,
        press_key: PressKeyAction,
        scroll: ScrollAction,
        take_screenshot: TakeScreenshotAction,
        type_text: TypeTextAction,
        wait: WaitAction,
    })
    .transform<Scrapybara.Action>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace Action {
    export type Raw =
        | Action.ClickMouse
        | Action.DragMouse
        | Action.GetCursorPosition
        | Action.MoveMouse
        | Action.PressKey
        | Action.Scroll
        | Action.TakeScreenshot
        | Action.TypeText
        | Action.Wait;

    export interface ClickMouse extends ClickMouseAction.Raw {
        action: "click_mouse";
    }

    export interface DragMouse extends DragMouseAction.Raw {
        action: "drag_mouse";
    }

    export interface GetCursorPosition extends GetCursorPositionAction.Raw {
        action: "get_cursor_position";
    }

    export interface MoveMouse extends MoveMouseAction.Raw {
        action: "move_mouse";
    }

    export interface PressKey extends PressKeyAction.Raw {
        action: "press_key";
    }

    export interface Scroll extends ScrollAction.Raw {
        action: "scroll";
    }

    export interface TakeScreenshot extends TakeScreenshotAction.Raw {
        action: "take_screenshot";
    }

    export interface TypeText extends TypeTextAction.Raw {
        action: "type_text";
    }

    export interface Wait extends WaitAction.Raw {
        action: "wait";
    }
}
