/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const ActResponse: core.serialization.ObjectSchema<serializers.ActResponse.Raw, Scrapybara.ActResponse> =
    core.serialization.object({
        output: core.serialization.string(),
        screenshot: core.serialization.string().optional(),
    });

export declare namespace ActResponse {
    interface Raw {
        output: string;
        screenshot?: string | null;
    }
}
