/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const AuthStateResponse: core.serialization.ObjectSchema<
    serializers.AuthStateResponse.Raw,
    Scrapybara.AuthStateResponse
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string().optional(),
});

export declare namespace AuthStateResponse {
    export interface Raw {
        id: string;
        name?: string | null;
    }
}
