/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const BashResponse: core.serialization.ObjectSchema<serializers.BashResponse.Raw, Scrapybara.BashResponse> =
    core.serialization.object({
        output: core.serialization.string().optional(),
        error: core.serialization.string().optional(),
        base64Image: core.serialization.property("base64_image", core.serialization.string().optional()),
        system: core.serialization.string().optional(),
    });

export declare namespace BashResponse {
    export interface Raw {
        output?: string | null;
        error?: string | null;
        base64_image?: string | null;
        system?: string | null;
    }
}
