/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const BrowserAuthenticateResponse: core.serialization.ObjectSchema<
    serializers.BrowserAuthenticateResponse.Raw,
    Scrapybara.BrowserAuthenticateResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace BrowserAuthenticateResponse {
    export interface Raw {
        status: string;
    }
}
