/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ScrapybaraApi from "../../api/index";
import * as core from "../../core";

export const BrowserAuthenticateResponse: core.serialization.ObjectSchema<
    serializers.BrowserAuthenticateResponse.Raw,
    ScrapybaraApi.BrowserAuthenticateResponse
> = core.serialization.object({
    status: core.serialization.string(),
    authenticatedApps: core.serialization.property(
        "authenticated_apps",
        core.serialization.list(core.serialization.string())
    ),
});

export declare namespace BrowserAuthenticateResponse {
    interface Raw {
        status: string;
        authenticated_apps: string[];
    }
}
