/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const BrowserGetStreamUrlResponse: core.serialization.ObjectSchema<
    serializers.BrowserGetStreamUrlResponse.Raw,
    Scrapybara.BrowserGetStreamUrlResponse
> = core.serialization.object({
    streamUrl: core.serialization.property("stream_url", core.serialization.string()),
});

export declare namespace BrowserGetStreamUrlResponse {
    export interface Raw {
        stream_url: string;
    }
}
