/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const CellType: core.serialization.Schema<serializers.CellType.Raw, Scrapybara.CellType> =
    core.serialization.enum_(["code", "markdown", "raw"]);

export declare namespace CellType {
    export type Raw = "code" | "markdown" | "raw";
}
