/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const ClickMouseActionClickType: core.serialization.Schema<
    serializers.ClickMouseActionClickType.Raw,
    Scrapybara.ClickMouseActionClickType
> = core.serialization.enum_(["down", "up", "click"]);

export declare namespace ClickMouseActionClickType {
    export type Raw = "down" | "up" | "click";
}
