/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { Button } from "./Button";
import { ClickMouseActionClickType } from "./ClickMouseActionClickType";

export const ClickMouseAction: core.serialization.ObjectSchema<
    serializers.ClickMouseAction.Raw,
    Scrapybara.ClickMouseAction
> = core.serialization.object({
    button: Button,
    clickType: core.serialization.property("click_type", ClickMouseActionClickType.optional()),
    coordinates: core.serialization.list(core.serialization.number()).optional(),
    numClicks: core.serialization.property("num_clicks", core.serialization.number().optional()),
    holdKeys: core.serialization.property("hold_keys", core.serialization.list(core.serialization.string()).optional()),
    screenshot: core.serialization.boolean().optional(),
});

export declare namespace ClickMouseAction {
    export interface Raw {
        button: Button.Raw;
        click_type?: ClickMouseActionClickType.Raw | null;
        coordinates?: number[] | null;
        num_clicks?: number | null;
        hold_keys?: string[] | null;
        screenshot?: boolean | null;
    }
}
