/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { Action } from "./Action";

export const ComputerRequest: core.serialization.ObjectSchema<
    serializers.ComputerRequest.Raw,
    Scrapybara.ComputerRequest
> = core.serialization.object({
    action: Action,
    screenshot: core.serialization.boolean().optional(),
});

export declare namespace ComputerRequest {
    export interface Raw {
        action: Action.Raw;
        screenshot?: boolean | null;
    }
}
