/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const DragMouseAction: core.serialization.ObjectSchema<
    serializers.DragMouseAction.Raw,
    Scrapybara.DragMouseAction
> = core.serialization.object({
    path: core.serialization.list(core.serialization.list(core.serialization.number())),
    holdKeys: core.serialization.property("hold_keys", core.serialization.list(core.serialization.string()).optional()),
    screenshot: core.serialization.boolean().optional(),
});

export declare namespace DragMouseAction {
    export interface Raw {
        path: number[][];
        hold_keys?: string[] | null;
        screenshot?: boolean | null;
    }
}
