/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const EnvGetResponse: core.serialization.ObjectSchema<
    serializers.EnvGetResponse.Raw,
    Scrapybara.EnvGetResponse
> = core.serialization.object({
    variables: core.serialization.record(core.serialization.string(), core.serialization.string()),
});

export declare namespace EnvGetResponse {
    export interface Raw {
        variables: Record<string, string>;
    }
}
