/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const EnvResponse: core.serialization.ObjectSchema<serializers.EnvResponse.Raw, Scrapybara.EnvResponse> =
    core.serialization.object({
        status: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace EnvResponse {
    export interface Raw {
        status: string;
        message: string;
    }
}
