/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const ExecuteCellRequest: core.serialization.ObjectSchema<
    serializers.ExecuteCellRequest.Raw,
    Scrapybara.ExecuteCellRequest
> = core.serialization.object({
    timeout: core.serialization.number().optional(),
});

export declare namespace ExecuteCellRequest {
    export interface Raw {
        timeout?: number | null;
    }
}
