/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const ExposePortResponse: core.serialization.ObjectSchema<
    serializers.ExposePortResponse.Raw,
    Scrapybara.ExposePortResponse
> = core.serialization.object({
    status: core.serialization.string(),
    publicUrl: core.serialization.property("public_url", core.serialization.string()),
});

export declare namespace ExposePortResponse {
    export interface Raw {
        status: string;
        public_url: string;
    }
}
