/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const FileReadResponse: core.serialization.ObjectSchema<
    serializers.FileReadResponse.Raw,
    Scrapybara.FileReadResponse
> = core.serialization.object({
    content: core.serialization.string(),
});

export declare namespace FileReadResponse {
    interface Raw {
        content: string;
    }
}
