/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const FileDownloadResponse: core.serialization.ObjectSchema<
    serializers.FileDownloadResponse.Raw,
    Scrapybara.FileDownloadResponse
> = core.serialization.object({
    content: core.serialization.string(),
});

export declare namespace FileDownloadResponse {
    export interface Raw {
        content: string;
    }
}
