/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const GetCursorPositionAction: core.serialization.ObjectSchema<
    serializers.GetCursorPositionAction.Raw,
    Scrapybara.GetCursorPositionAction
> = core.serialization.object({});

export declare namespace GetCursorPositionAction {
    export interface Raw {}
}
