/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { GetInstanceResponseInstanceType } from "./GetInstanceResponseInstanceType";
import { Status } from "./Status";

export const GetInstanceResponse: core.serialization.ObjectSchema<
    serializers.GetInstanceResponse.Raw,
    Scrapybara.GetInstanceResponse
> = core.serialization.object({
    id: core.serialization.string(),
    launchTime: core.serialization.property("launch_time", core.serialization.date()),
    instanceType: core.serialization.property("instance_type", GetInstanceResponseInstanceType),
    status: Status,
});

export declare namespace GetInstanceResponse {
    export interface Raw {
        id: string;
        launch_time: string;
        instance_type: GetInstanceResponseInstanceType.Raw;
        status: Status.Raw;
    }
}
