/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const GetInstanceResponseInstanceType: core.serialization.Schema<
    serializers.GetInstanceResponseInstanceType.Raw,
    Scrapybara.GetInstanceResponseInstanceType
> = core.serialization.enum_(["ubuntu", "browser", "windows"]);

export declare namespace GetInstanceResponseInstanceType {
    export type Raw = "ubuntu" | "browser" | "windows";
}
