/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const InstanceGetStreamUrlResponse: core.serialization.ObjectSchema<
    serializers.InstanceGetStreamUrlResponse.Raw,
    Scrapybara.InstanceGetStreamUrlResponse
> = core.serialization.object({
    streamUrl: core.serialization.property("stream_url", core.serialization.string()),
});

export declare namespace InstanceGetStreamUrlResponse {
    export interface Raw {
        stream_url: string;
    }
}
