/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const KernelInfo: core.serialization.ObjectSchema<serializers.KernelInfo.Raw, Scrapybara.KernelInfo> =
    core.serialization.object({
        name: core.serialization.string(),
        displayName: core.serialization.property("display_name", core.serialization.string()),
        language: core.serialization.string(),
    });

export declare namespace KernelInfo {
    export interface Raw {
        name: string;
        display_name: string;
        language: string;
    }
}
