/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const MoveMouseAction: core.serialization.ObjectSchema<
    serializers.MoveMouseAction.Raw,
    Scrapybara.MoveMouseAction
> = core.serialization.object({
    coordinates: core.serialization.list(core.serialization.number()),
    holdKeys: core.serialization.property("hold_keys", core.serialization.list(core.serialization.string()).optional()),
    screenshot: core.serialization.boolean().optional(),
});

export declare namespace MoveMouseAction {
    export interface Raw {
        coordinates: number[];
        hold_keys?: string[] | null;
        screenshot?: boolean | null;
    }
}
