/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const NetlifyDeployResponse: core.serialization.ObjectSchema<
    serializers.NetlifyDeployResponse.Raw,
    Scrapybara.NetlifyDeployResponse
> = core.serialization.object({
    output: core.serialization.string().optional(),
    error: core.serialization.string().optional(),
    siteUrl: core.serialization.property("site_url", core.serialization.string().optional()),
});

export declare namespace NetlifyDeployResponse {
    export interface Raw {
        output?: string | null;
        error?: string | null;
        site_url?: string | null;
    }
}
