/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { CellType } from "./CellType";

export const NotebookCell: core.serialization.ObjectSchema<serializers.NotebookCell.Raw, Scrapybara.NotebookCell> =
    core.serialization.object({
        id: core.serialization.string(),
        type: CellType,
        content: core.serialization.string(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        outputs: core.serialization
            .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
            .optional(),
        executionCount: core.serialization.property("execution_count", core.serialization.number().optional()),
    });

export declare namespace NotebookCell {
    export interface Raw {
        id: string;
        type: CellType.Raw;
        content: string;
        metadata?: Record<string, unknown> | null;
        outputs?: Record<string, unknown>[] | null;
        execution_count?: number | null;
    }
}
