/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";
import { NotebookCell } from "./NotebookCell";

export const Notebook: core.serialization.ObjectSchema<serializers.Notebook.Raw, Scrapybara.Notebook> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        kernelName: core.serialization.property("kernel_name", core.serialization.string()),
        cells: core.serialization.list(NotebookCell),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace Notebook {
    export interface Raw {
        id: string;
        name: string;
        kernel_name: string;
        cells: NotebookCell.Raw[];
        metadata?: Record<string, unknown> | null;
    }
}
