/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const PressKeyAction: core.serialization.ObjectSchema<
    serializers.PressKeyAction.Raw,
    Scrapybara.PressKeyAction
> = core.serialization.object({
    keys: core.serialization.list(core.serialization.string()),
    duration: core.serialization.number().optional(),
    screenshot: core.serialization.boolean().optional(),
});

export declare namespace PressKeyAction {
    export interface Raw {
        keys: string[];
        duration?: number | null;
        screenshot?: boolean | null;
    }
}
