/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const SaveBrowserAuthResponse: core.serialization.ObjectSchema<
    serializers.SaveBrowserAuthResponse.Raw,
    Scrapybara.SaveBrowserAuthResponse
> = core.serialization.object({
    status: core.serialization.string(),
    authStateId: core.serialization.property("auth_state_id", core.serialization.string()),
    name: core.serialization.string().optional(),
});

export declare namespace SaveBrowserAuthResponse {
    export interface Raw {
        status: string;
        auth_state_id: string;
        name?: string | null;
    }
}
