/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const ScrapeResponse: core.serialization.ObjectSchema<
    serializers.ScrapeResponse.Raw,
    Scrapybara.ScrapeResponse
> = core.serialization.object({
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    screenshot: core.serialization.string().optional(),
});

export declare namespace ScrapeResponse {
    interface Raw {
        data: Record<string, unknown>;
        screenshot?: string | null;
    }
}
