/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const ScrollAction: core.serialization.ObjectSchema<serializers.ScrollAction.Raw, Scrapybara.ScrollAction> =
    core.serialization.object({
        coordinates: core.serialization.list(core.serialization.number()).optional(),
        deltaX: core.serialization.property("delta_x", core.serialization.number().optional()),
        deltaY: core.serialization.property("delta_y", core.serialization.number().optional()),
        holdKeys: core.serialization.property(
            "hold_keys",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        screenshot: core.serialization.boolean().optional(),
    });

export declare namespace ScrollAction {
    export interface Raw {
        coordinates?: number[] | null;
        delta_x?: number | null;
        delta_y?: number | null;
        hold_keys?: string[] | null;
        screenshot?: boolean | null;
    }
}
