/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const SnapshotResponse: core.serialization.ObjectSchema<
    serializers.SnapshotResponse.Raw,
    Scrapybara.SnapshotResponse
> = core.serialization.object({
    snapshotId: core.serialization.property("snapshot_id", core.serialization.string()),
});

export declare namespace SnapshotResponse {
    export interface Raw {
        snapshot_id: string;
    }
}
