/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const StartBrowserResponse: core.serialization.ObjectSchema<
    serializers.StartBrowserResponse.Raw,
    Scrapybara.StartBrowserResponse
> = core.serialization.object({
    cdpUrl: core.serialization.property("cdp_url", core.serialization.string()),
    streamUrl: core.serialization.property("stream_url", core.serialization.string().optional()),
});

export declare namespace StartBrowserResponse {
    export interface Raw {
        cdp_url: string;
        stream_url?: string | null;
    }
}
