/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const Status: core.serialization.Schema<serializers.Status.Raw, Scrapybara.Status> = core.serialization.enum_([
    "deploying",
    "running",
    "paused",
    "terminated",
    "error",
    "warm_pool",
]);

export declare namespace Status {
    export type Raw = "deploying" | "running" | "paused" | "terminated" | "error" | "warm_pool";
}
