/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as ScrapybaraApi from "../../api/index";
import * as core from "../../core";

export const StopBrowserResponse: core.serialization.ObjectSchema<
    serializers.StopBrowserResponse.Raw,
    ScrapybaraApi.StopBrowserResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace StopBrowserResponse {
    interface Raw {
        status: string;
    }
}
