/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const StopInstanceResponse: core.serialization.ObjectSchema<
    serializers.StopInstanceResponse.Raw,
    Scrapybara.StopInstanceResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace StopInstanceResponse {
    export interface Raw {
        status: string;
    }
}
