/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const SuccessResponse: core.serialization.ObjectSchema<
    serializers.SuccessResponse.Raw,
    Scrapybara.SuccessResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string(),
});

export declare namespace SuccessResponse {
    export interface Raw {
        success: boolean;
        message: string;
    }
}
