/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const TakeScreenshotAction: core.serialization.ObjectSchema<
    serializers.TakeScreenshotAction.Raw,
    Scrapybara.TakeScreenshotAction
> = core.serialization.object({});

export declare namespace TakeScreenshotAction {
    export interface Raw {}
}
