/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const TypeTextAction: core.serialization.ObjectSchema<
    serializers.TypeTextAction.Raw,
    Scrapybara.TypeTextAction
> = core.serialization.object({
    text: core.serialization.string(),
    holdKeys: core.serialization.property("hold_keys", core.serialization.list(core.serialization.string()).optional()),
    screenshot: core.serialization.boolean().optional(),
});

export declare namespace TypeTextAction {
    export interface Raw {
        text: string;
        hold_keys?: string[] | null;
        screenshot?: boolean | null;
    }
}
