/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const UploadResponse: core.serialization.ObjectSchema<
    serializers.UploadResponse.Raw,
    Scrapybara.UploadResponse
> = core.serialization.object({
    filename: core.serialization.string(),
    path: core.serialization.string(),
    mediaType: core.serialization.property("media_type", core.serialization.string().optional()),
});

export declare namespace UploadResponse {
    export interface Raw {
        filename: string;
        path: string;
        media_type?: string | null;
    }
}
