/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Scrapybara from "../../api/index";
import * as core from "../../core";

export const WaitAction: core.serialization.ObjectSchema<serializers.WaitAction.Raw, Scrapybara.WaitAction> =
    core.serialization.object({
        duration: core.serialization.number(),
        screenshot: core.serialization.boolean().optional(),
    });

export declare namespace WaitAction {
    export interface Raw {
        duration: number;
        screenshot?: boolean | null;
    }
}
