/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as ScrapybaraApi from "../../../../api/index";
import * as core from "../../../../core";

export const DeploymentConfigInstanceType: core.serialization.Schema<
    serializers.DeploymentConfigInstanceType.Raw,
    ScrapybaraApi.DeploymentConfigInstanceType
> = core.serialization.enum_(["small", "medium", "large"]);

export declare namespace DeploymentConfigInstanceType {
    type Raw = "small" | "medium" | "large";
}
