/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteScriptStreamingResponse
 */
export interface ExecuteScriptStreamingResponse {
    /**
     * The current execution status (e.g., 'in_progress', 'completed', 'error').
     * @type {string}
     * @memberof ExecuteScriptStreamingResponse
     */
    status: string;
    /**
     * Additional details about the current execution status or errors.
     * @type {string}
     * @memberof ExecuteScriptStreamingResponse
     */
    statusDescription: string;
    /**
     * The data extracted by the script.
     * @type {object}
     * @memberof ExecuteScriptStreamingResponse
     */
    result?: object;
    /**
     * 
     * @type {boolean}
     * @memberof ExecuteScriptStreamingResponse
     */
    streaming: boolean;
}

/**
 * Check if a given object implements the ExecuteScriptStreamingResponse interface.
 */
export function instanceOfExecuteScriptStreamingResponse(value: object): value is ExecuteScriptStreamingResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusDescription' in value) || value['statusDescription'] === undefined) return false;
    if (!('streaming' in value) || value['streaming'] === undefined) return false;
    return true;
}

export function ExecuteScriptStreamingResponseFromJSON(json: any): ExecuteScriptStreamingResponse {
    return ExecuteScriptStreamingResponseFromJSONTyped(json, false);
}

export function ExecuteScriptStreamingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteScriptStreamingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statusDescription': json['status_description'],
        'result': json['result'] == null ? undefined : json['result'],
        'streaming': json['streaming'],
    };
}

export function ExecuteScriptStreamingResponseToJSON(value?: ExecuteScriptStreamingResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'status_description': value['statusDescription'],
        'result': value['result'],
        'streaming': value['streaming'],
    };
}

