/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteScriptNonStreamingResponse
 */
export interface ExecuteScriptNonStreamingResponse {
    /**
     * The execution status (e.g., 'completed', 'error').
     * @type {string}
     * @memberof ExecuteScriptNonStreamingResponse
     */
    status: string;
    /**
     * Additional details about the execution status or errors.
     * @type {string}
     * @memberof ExecuteScriptNonStreamingResponse
     */
    statusDescription: string;
    /**
     * The data extracted by the script.
     * @type {object}
     * @memberof ExecuteScriptNonStreamingResponse
     */
    result: object;
    /**
     * 
     * @type {boolean}
     * @memberof ExecuteScriptNonStreamingResponse
     */
    streaming: boolean;
}

/**
 * Check if a given object implements the ExecuteScriptNonStreamingResponse interface.
 */
export function instanceOfExecuteScriptNonStreamingResponse(value: object): value is ExecuteScriptNonStreamingResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusDescription' in value) || value['statusDescription'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('streaming' in value) || value['streaming'] === undefined) return false;
    return true;
}

export function ExecuteScriptNonStreamingResponseFromJSON(json: any): ExecuteScriptNonStreamingResponse {
    return ExecuteScriptNonStreamingResponseFromJSONTyped(json, false);
}

export function ExecuteScriptNonStreamingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteScriptNonStreamingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statusDescription': json['status_description'],
        'result': json['result'],
        'streaming': json['streaming'],
    };
}

export function ExecuteScriptNonStreamingResponseToJSON(value?: ExecuteScriptNonStreamingResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'status_description': value['statusDescription'],
        'result': value['result'],
        'streaming': value['streaming'],
    };
}

