/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteScriptRequest
 */
export interface ExecuteScriptRequest {
    /**
     * Unique identifier of the script to be executed.
     * @type {string}
     * @memberof ExecuteScriptRequest
     */
    scriptId: string;
    /**
     * If true, the execution results will be streamed as they're generated.
     * @type {boolean}
     * @memberof ExecuteScriptRequest
     */
    streaming?: boolean;
    /**
     * If true, applies advanced processing to improve data extraction results.
     * @type {boolean}
     * @memberof ExecuteScriptRequest
     */
    magic?: boolean;
    /**
     * Optional URL to override the script's default target URL.
     * @type {string}
     * @memberof ExecuteScriptRequest
     */
    url?: string;
}

/**
 * Check if a given object implements the ExecuteScriptRequest interface.
 */
export function instanceOfExecuteScriptRequest(value: object): value is ExecuteScriptRequest {
    if (!('scriptId' in value) || value['scriptId'] === undefined) return false;
    return true;
}

export function ExecuteScriptRequestFromJSON(json: any): ExecuteScriptRequest {
    return ExecuteScriptRequestFromJSONTyped(json, false);
}

export function ExecuteScriptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteScriptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'scriptId': json['script_id'],
        'streaming': json['streaming'] == null ? undefined : json['streaming'],
        'magic': json['magic'] == null ? undefined : json['magic'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ExecuteScriptRequestToJSON(value?: ExecuteScriptRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'script_id': value['scriptId'],
        'streaming': value['streaming'],
        'magic': value['magic'],
        'url': value['url'],
    };
}

