/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FetchHtmlResponse
 */
export interface FetchHtmlResponse {
    /**
     * The raw HTML content of the requested URL.
     * @type {string}
     * @memberof FetchHtmlResponse
     */
    html?: string;
}

/**
 * Check if a given object implements the FetchHtmlResponse interface.
 */
export function instanceOfFetchHtmlResponse(value: object): value is FetchHtmlResponse {
    return true;
}

export function FetchHtmlResponseFromJSON(json: any): FetchHtmlResponse {
    return FetchHtmlResponseFromJSONTyped(json, false);
}

export function FetchHtmlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchHtmlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'] == null ? undefined : json['html'],
    };
}

export function FetchHtmlResponseToJSON(value?: FetchHtmlResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'html': value['html'],
    };
}

