/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateScriptStreamingResponse
 */
export interface GenerateScriptStreamingResponse {
    /**
     * Unique identifier for the generated script.
     * @type {string}
     * @memberof GenerateScriptStreamingResponse
     */
    scriptId: string;
    /**
     * The current status of script generation (e.g., 'in_progress', 'completed', 'error').
     * @type {string}
     * @memberof GenerateScriptStreamingResponse
     */
    status: string;
    /**
     * Additional details about the generation status or errors.
     * @type {string}
     * @memberof GenerateScriptStreamingResponse
     */
    statusDescription: string;
    /**
     * The current version of the generated script.
     * @type {string}
     * @memberof GenerateScriptStreamingResponse
     */
    currentScript?: string;
    /**
     * The result of executing the current version of the script.
     * @type {string}
     * @memberof GenerateScriptStreamingResponse
     */
    currentScriptExecutionResult?: string;
    /**
     * Explanation of the reasoning behind the current script version.
     * @type {string}
     * @memberof GenerateScriptStreamingResponse
     */
    reasoning?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateScriptStreamingResponse
     */
    streaming: boolean;
}

/**
 * Check if a given object implements the GenerateScriptStreamingResponse interface.
 */
export function instanceOfGenerateScriptStreamingResponse(value: object): value is GenerateScriptStreamingResponse {
    if (!('scriptId' in value) || value['scriptId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusDescription' in value) || value['statusDescription'] === undefined) return false;
    if (!('streaming' in value) || value['streaming'] === undefined) return false;
    return true;
}

export function GenerateScriptStreamingResponseFromJSON(json: any): GenerateScriptStreamingResponse {
    return GenerateScriptStreamingResponseFromJSONTyped(json, false);
}

export function GenerateScriptStreamingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateScriptStreamingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scriptId': json['script_id'],
        'status': json['status'],
        'statusDescription': json['status_description'],
        'currentScript': json['current_script'] == null ? undefined : json['current_script'],
        'currentScriptExecutionResult': json['current_script_execution_result'] == null ? undefined : json['current_script_execution_result'],
        'reasoning': json['reasoning'] == null ? undefined : json['reasoning'],
        'streaming': json['streaming'],
    };
}

export function GenerateScriptStreamingResponseToJSON(value?: GenerateScriptStreamingResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'script_id': value['scriptId'],
        'status': value['status'],
        'status_description': value['statusDescription'],
        'current_script': value['currentScript'],
        'current_script_execution_result': value['currentScriptExecutionResult'],
        'reasoning': value['reasoning'],
        'streaming': value['streaming'],
    };
}

