/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateScriptRequest
 */
export interface GenerateScriptRequest {
    /**
     * The target URL for the script.
     * @type {string}
     * @memberof GenerateScriptRequest
     */
    url: string;
    /**
     * The action to be performed by the script.
     * @type {string}
     * @memberof GenerateScriptRequest
     */
    command: string;
    /**
     * Optional step-by-step instructions for complex actions.
     * @type {Array<string>}
     * @memberof GenerateScriptRequest
     */
    steps?: Array<string>;
    /**
     * If true, the response will be streamed as it's generated.
     * @type {boolean}
     * @memberof GenerateScriptRequest
     */
    streaming?: boolean;
    /**
     * Optional schema defining the structure of input data.
     * @type {object}
     * @memberof GenerateScriptRequest
     */
    inputSchema?: object;
    /**
     * Optional schema defining the expected structure of output data.
     * @type {object}
     * @memberof GenerateScriptRequest
     */
    outputSchema?: object;
}

/**
 * Check if a given object implements the GenerateScriptRequest interface.
 */
export function instanceOfGenerateScriptRequest(value: object): value is GenerateScriptRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function GenerateScriptRequestFromJSON(json: any): GenerateScriptRequest {
    return GenerateScriptRequestFromJSONTyped(json, false);
}

export function GenerateScriptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateScriptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'command': json['command'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'streaming': json['streaming'] == null ? undefined : json['streaming'],
        'inputSchema': json['input_schema'] == null ? undefined : json['input_schema'],
        'outputSchema': json['output_schema'] == null ? undefined : json['output_schema'],
    };
}

export function GenerateScriptRequestToJSON(value?: GenerateScriptRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'command': value['command'],
        'steps': value['steps'],
        'streaming': value['streaming'],
        'input_schema': value['inputSchema'],
        'output_schema': value['outputSchema'],
    };
}

