/* tslint:disable */
/* eslint-disable */
/**
 * Scrapybara API
 * Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetScriptResponse
 */
export interface GetScriptResponse {
    /**
     * Unique identifier of the script.
     * @type {string}
     * @memberof GetScriptResponse
     */
    id?: string;
    /**
     * The target URL for the script.
     * @type {string}
     * @memberof GetScriptResponse
     */
    url?: string;
    /**
     * The original action or instructions.
     * @type {string}
     * @memberof GetScriptResponse
     */
    command?: string;
    /**
     * Detailed steps for the action.
     * @type {object}
     * @memberof GetScriptResponse
     */
    steps?: object;
    /**
     * The actual code content of the script.
     * @type {string}
     * @memberof GetScriptResponse
     */
    content?: string;
    /**
     * Current status of the script (e.g., 'pending', 'completed', 'error').
     * @type {string}
     * @memberof GetScriptResponse
     */
    status?: string;
    /**
     * Additional details about the script's status.
     * @type {string}
     * @memberof GetScriptResponse
     */
    statusDescription?: string;
}

/**
 * Check if a given object implements the GetScriptResponse interface.
 */
export function instanceOfGetScriptResponse(value: object): value is GetScriptResponse {
    return true;
}

export function GetScriptResponseFromJSON(json: any): GetScriptResponse {
    return GetScriptResponseFromJSONTyped(json, false);
}

export function GetScriptResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetScriptResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'command': json['command'] == null ? undefined : json['command'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'content': json['content'] == null ? undefined : json['content'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusDescription': json['status_description'] == null ? undefined : json['status_description'],
    };
}

export function GetScriptResponseToJSON(value?: GetScriptResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'url': value['url'],
        'command': value['command'],
        'steps': value['steps'],
        'content': value['content'],
        'status': value['status'],
        'status_description': value['statusDescription'],
    };
}

