/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client } from "./api/resources/client/client/Client";
import { Instance } from "./api/resources/instance/client/Client";
import { Browser } from "./api/resources/browser/client/Client";

export declare namespace ScrapybaraApiClient {
    interface Options {
        environment?: core.Supplier<environments.ScrapybaraApiEnvironment | string>;
        /** Override the authorization header */
        authorization: core.Supplier<string>;
    }

    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the authorization header */
        authorization?: string;
    }
}

export class ScrapybaraApiClient {
    constructor(protected readonly _options: ScrapybaraApiClient.Options) {}

    protected _client: Client | undefined;

    public get client(): Client {
        return (this._client ??= new Client(this._options));
    }

    protected _instance: Instance | undefined;

    public get instance(): Instance {
        return (this._instance ??= new Instance(this._options));
    }

    protected _browser: Browser | undefined;

    public get browser(): Browser {
        return (this._browser ??= new Browser(this._options));
    }
}
