/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ScrapybaraEnvironment = {
    Default: "https://api.scrapybara.com",
} as const;

export type ScrapybaraEnvironment = typeof ScrapybaraEnvironment.Default;
