/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ScrapybaraApiEnvironment = {
    Default: "https://api.scrapybara.com",
} as const;

export type ScrapybaraApiEnvironment = typeof ScrapybaraApiEnvironment.Default;
