/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";
import { CellType } from "../../../../types/CellType";

export const AddCellRequest: core.serialization.Schema<serializers.AddCellRequest.Raw, Scrapybara.AddCellRequest> =
    core.serialization.object({
        type: CellType,
        content: core.serialization.string(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace AddCellRequest {
    export interface Raw {
        type: CellType.Raw;
        content: string;
        metadata?: Record<string, unknown> | null;
    }
}
