/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Scrapybara from "../../../../../api/index";
import * as core from "../../../../../core";

export const CreateNotebookRequest: core.serialization.Schema<
    serializers.CreateNotebookRequest.Raw,
    Scrapybara.CreateNotebookRequest
> = core.serialization.object({
    name: core.serialization.string(),
    kernelName: core.serialization.property("kernel_name", core.serialization.string().optional()),
});

export declare namespace CreateNotebookRequest {
    export interface Raw {
        name: string;
        kernel_name?: string | null;
    }
}
