/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Scrapybara from "../../../../index";

/**
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 */
export interface ActRequest {
    cmd: string;
    includeScreenshot?: boolean;
    model?: Scrapybara.Model;
}
