/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         cmd: "cmd"
 *     }
 */
export interface ScrapeRequest {
    cmd: string;
    schema?: Record<string, unknown>;
    includeScreenshot?: boolean;
    model?: "claude";
}
